export const defaultSchema = {
  eventName: 'City Marathon 2026',
  tagline: 'Run For The Win! Join the biggest marathon event this year.',
  description:
    'Bersiaplah untuk memacu adrenalin di City Marathon 2026. Taklukan tantangan, cetak rekor pribadi, dan rasakan euforia lari bersama ribuan pelari lainnya di lintasan ikonik jantung kota.',
  location: 'City Center Start/Finish',
  date: '19 Oktober 2026',
  poster: '/new_running_poster.png',
  highlights: [
    { label: 'Kategori Lari', value: '5K, 10K, HM, FM' },
    { label: 'Total Hadiah', value: 'Rp 200 Juta' },
    { label: 'Benefit Eksklusif', value: 'Jersey & Medali' },
  ],
  features: [
    { title: 'Lintasan Steril & Aman', description: 'Rute lari di jantung kota dengan pengawalan penuh dan water station di setiap 2.5km.' },
    { title: 'Timing System Akurat', description: 'Sistem pencatatan waktu real-time menggunakan teknologi chip untuk akurasi maksimal.' },
    { title: 'Race Kit & Medali', description: 'Jersey drifit premium, nomor BIB, dan medali finisher eksklusif untuk setiap peserta.' },
  ],
  fields: [
    {
      id: 'full-name',
      label: 'Nama Lengkap',
      type: 'text',
      required: true,
      placeholder: 'Masukkan nama lengkap',
      options: '',
    },
    {
      id: 'email',
      label: 'Email',
      type: 'email',
      required: true,
      placeholder: 'nama@email.com',
      options: '',
    },
    {
      id: 'phone',
      label: 'Nomor WhatsApp',
      type: 'tel',
      required: true,
      placeholder: '08xxxxxxxxxx',
      options: '',
    },
    {
      id: 'category',
      label: 'Kategori Peserta',
      type: 'select',
      required: true,
      placeholder: '',
      options: 'Pelajar, Mahasiswa, Umum, Komunitas',
    },
    {
      id: 'motivation',
      label: 'Motivasi Mengikuti Event',
      type: 'textarea',
      required: false,
      placeholder: 'Ceritakan singkat alasan Anda',
      options: '',
    },
  ],
}
