export const defaultSchema = {
  eventName: 'RB SILENT BEAT RUN 2026',
  tagline: 'Run the rhythm. Feel the beat. Experience the silence.',
  description:
    'Sebuah cara baru menikmati lari hadir pertama kalinya di Solo. Bukan sekadar fun run—ini adalah pengalaman. RB Silent Beat Run menggabungkan energi lari dengan ritme musik dalam satu frekuensi yang sama. Setiap langkah bukan hanya tentang jarak, tapi tentang rasa. Dengan headphone yang terhubung langsung ke DJ, kamu akan berlari dalam duniamu sendiri—tanpa distraksi, hanya kamu, beat, dan vibe yang menyatu. Ini bukan lomba soal siapa tercepat. Ini tentang menikmati perjalanan. Ini tentang merasakan momen.',
  location: 'Ruang Bahagia, Lokananta Solo',
  date: '29 April 2026',
  poster: '/new_running_poster.png',
  highlights: [
    { label: 'Kategori Lari', value: 'Fun Run 5K' },
    { label: 'Benefit Eksklusif', value: 'T-Shirt Cotton' },
  ],
  features: [
    { title: 'Silent Run Experience', description: 'Nikmati pengalaman lari dengan headphone yang terhubung langsung ke DJ, menghadirkan beat dan vibe yang menyatu di setiap langkah.' },
    { title: 'Fun Run 5K', description: 'Berlari santai dalam format 5K yang fokus pada pengalaman, momen, dan keseruan menikmati ritme sepanjang rute.' },
    { title: 'Exclusive Event Tee', description: 'Setiap peserta mendapatkan benefit eksklusif berupa T-Shirt Cotton sebagai bagian dari pengalaman event.' },
  ],
  fields: [
    {
      id: 'full-name',
      label: 'Nama Lengkap',
      type: 'text',
      required: true,
      placeholder: 'Masukkan nama lengkap',
      options: '',
    },
    {
      id: 'email',
      label: 'Email',
      type: 'email',
      required: true,
      placeholder: 'nama@email.com',
      options: '',
    },
    {
      id: 'phone',
      label: 'Nomer Whatsapp',
      type: 'tel',
      required: true,
      placeholder: '08xxxxxxxxxx',
      options: '',
    },
    {
      id: 'tshirt-size',
      label: 'Size T-Shirt',
      type: 'select',
      required: true,
      placeholder: '',
      options: 'S, M, L, XL',
    },
  ],
  emailConfig: {
    enabled: false,
    fromName: 'RB SILENT BEAT RUN 2026',
    fromEmail: 'noreply@yourdomain.com',
    replyTo: 'support@yourdomain.com',
    participantEmail: {
      enabled: true,
      subject: 'Konfirmasi Pendaftaran - {{eventName}}',
      template: {
        headerColor: '#2563eb',
        logoUrl: '',
        greeting: 'Terima kasih telah mendaftar!',
        bodyText: 'Pendaftaran Anda untuk {{eventName}} telah kami terima. Kami sangat senang Anda bergabung dengan kami!',
        instructions: 'Langkah selanjutnya:\n1. Cek email ini sebagai bukti pendaftaran\n2. Simpan nomor registrasi Anda: {{registrationId}}\n3. Tunggu konfirmasi pembayaran dari tim kami\n4. Jika ada pertanyaan, hubungi kami di {{replyTo}}',
        footerText: 'Email ini dikirim otomatis. Jika ada pertanyaan, silakan hubungi kami di {{replyTo}}',
        showEventDetails: true,
        showRegistrationData: true,
      },
    },
    adminEmail: {
      enabled: true,
      subject: 'Pendaftaran Baru - {{participantName}}',
      template: {
        headerColor: '#059669',
        logoUrl: '',
        greeting: 'Pendaftaran Baru Diterima',
        bodyText: 'Ada peserta baru yang mendaftar untuk {{eventName}}.',
        instructions: '',
        footerText: 'Notifikasi otomatis dari sistem pendaftaran.',
        showEventDetails: false,
        showRegistrationData: true,
      },
    },
  },
}
